### PR TITLE
Add TootDesk, iOS client

### PR DESCRIPTION
**Pull request by cutls**
Add TootDesk for iOS

### CODE REVIEW

**Comment by cutls** [comment]
Maybe now that you have the official Mastodon app, You don't need third-party apps that don't help your gGmbH advertise. Elon drove tapbot to Mastodon, but I can't tell the difference between you and Elon now.

**Comment by cutls** [comment]
Ivory: 7 hours to merge
My app: how long should I wait? Mastodon does not need TootDesk?

Maybe now that you have the official Mastodon app, You don't need third-party apps that don't help your gGmbH advertise. Elon drove tapbot to Mastodon, but I can't tell the difference between you and Elon now.

**Comment by andypiper** [comment]
Apologies for the delay here, merged.

**Comment by andypiper** [comment]
The icon is very similar to another app (TheDesk) so you may want to do something to make it more distinct or separate.

**Pull request merged**
