### PR TITLE
Add Megalodon to apps

### LINKED ISSUE #293: Add Megalodon to Android apps
I have been using and loving Megalodon, a Mastodon app for Android that is based on the official app codebase but with its own branding, features, and personality. It would be nice to add it to the list of clients for Android, as it is always the one I recommend.

https://play.google.com/store/apps/details?id=org.joinmastodon.android.sk

### PR DESCRIPTION
**Pull request by cassidyjames**
Released on the Play Store on November 28, 2022 for Android. Fixes #293

### CODE REVIEW

**Comment by cassidyjames** [comment]
@Gargron I see you've merged several other apps since this PR; is there something I'm missing that would need to be resolved before this could be merged?

**Comment by jpkhawam** [comment]
Replying to +1 this PR. Megalodon is a seriously polished app that should be included on this list

**Comment by jpkhawam** [comment]
GitHub repo: https://github.com/sk22/megalodon
Playstore link: https://play.google.com/store/apps/details?id=org.joinmastodon.android.sk

**Comment by axb21** [comment]
@Gargron merge this! What are you waiting for?

**Comment by andypiper** [comment]
This has taken a while as we have been discussing how to list apps that are forks of other apps (whether the Mastodon-provided apps, or any others), as this could get confusing. I'm going to go ahead and merge this PR (when I've fixed the conflict right after I've typed this), but we've now added [contribution guidelines](https://github.com/mastodon/joinmastodon/blob/master/CONTRIBUTING.md) with a note that we are still thinking about this in the longer term and may do some more labelling or categorisation to avoid the lists getting too "noisy".

I've only relatively recently joined the team working on Dev Rel and we're a small group so we appreciate your patience and understanding. Happy to chat @andypiper@macaw.social if you need anything further.

**Comment by andypiper** [comment]
I will also note (and this is for the app author more than @cassidyjames who submitted this for the site) that the org name for the Android package `org.joinmastodon.android.sk` *may* be a source of confusion, although I admit I have not looked at how forks of Android apps usually get packaged i.e. if adding a suffix to an org ID, or changing it, is more common.

**Comment by andypiper** [comment]
bear with me as I work through the other PRs...

**Pull request merged**
