### PR TITLE
Reorder sign-up process options

### PR DESCRIPTION
**Pull request by jsoref**
This covers the third point of https://mastodon.social/@atomicpoet/109821361045588259

The original order is:
* all
* instant
* manual

I'm proposing to change it to:
* instant
* manual
* all

We expect that most users will want instant. Some will want manual. But, oddly, most users are least likely to want all.

### CODE REVIEW

**Comment by Gargron** [comment]
Why does the order in the dropdown matter? I imagine you'd just want to show instant ones by default instead of all.

However, the problem with that is that fewer/empty results might be more common, which is also not a good look.

**Comment by jsoref** [comment]
I need to spend some time figuring out how to change the default. I'll get back to this.

**Comment by jsoref** [comment]
When I add a filter or tune filters, I'll generally add text explaining to users that they're seeing a filtered view and hinting at how much they're missing out. But that's more than I'm up for doing in this round of PRs.

Lemme finish working on the run...

**Comment by jsoref** [comment]
As to why does the order matter...

The goal is for users to have the fastest/smoothest sign-up process possible.

One nice feature of Mastodons is that users can migrate, which means that *after* a user has joined a server, they can later migrate to one that requires manual registration. But, at least in the interim, it's valuable to get them onboarded and using _a_ mastodon.

**Pull request closed without merging**
