### PR TITLE
Add spaces around "en dash" and use unicode version in translation files

### LINKED ISSUE #246: HTML character codes, like `&mdash`, on translated pages
On https://joinmastodon.org/it/servers
`&mdash` gets inserted as normal text.

Screenshot from 2022-11-10 23-01-39

The same issues appears on every translated language.
Tested on the latest firefox on desktop and tested on brave for mobile.

### LINKED ISSUE #269: HTML-encoded characters are shown in non-english languages
For example, on https://joinmastodon.org/fr/servers I see:

> Mastodon n’est pas un site Web unique. Pour l’utiliser, vous devez créer un compte chez un fournisseur&mdash;nous les appelons serveurs&mdash;qui vous permettra d’entrer en contact avec d’autres personnes à travers Mastodon.

And in german https://joinmastodon.org/de/servers:

> Mastodon ist keine einzelne Webseite. Um es nutzen zu können, musst du ein Konto bei einem Anbieter erstellen &ndash; wir nennen sie Server &ndash; der dich mit anderen Personen über alle Mastodon-Instanzen hinweg vernetzen lässt.

I think the translated files should use the non-HTML-encoded character, and it will then be correctly encoded by the i18n library in the resulting page.

### PR DESCRIPTION
**Pull request by roydigerhund**
**Problem**
On https://joinmastodon.org/de/servers all languages besides the english one are displaying either `&mdash;` or `&ndash;` as plain text because the package `react-intl` does not support the conversion from `&ndash;` to `–`. To fix this we have to use the unicode version `\u2013` instead.
Additionally we have missing spaces before and after this character and only the german translation used the correct `–`, all other languages used the incorrect longer version `—` (Em Dash).

**Solution**
Replacing all `&ndash;` and `&mdash;` in json files with `\u2013` and adding spaces before and after the character. In the file `pages/servers.tsx` I'm still using the `&ndash;` because this implementation supports this spelling and not the other one.

**Additional Info**
In the translations `pl.json`, `ru.json`, `uk.json` and `zh.json` is a comma (in `zh.json` something similar) before or/and after the `en dash` and I'm not sure if this is the correct spelling in those languages.

**Linked Issues**
closes #269 
closes #246

### CODE REVIEW

**Comment by renchap** [comment]
Will fix #269

**Comment by roydigerhund** [comment]
Will fix #246 too.

**Comment by renchap** [comment]
@roydigerhund In your PR, you are updating the non-english locale files.

Your changes will be lost the next time @Gargron updates them from Crowdin (the translation tool used by the project).

You need to only include the changes in the `en` locale, then this locale needs to be imported into Crowdin, translations updated with the unicode character, and imported back into the project.

**Comment by roydigerhund** [comment]
@renchap hmm that's bad, I can't even change it in `en.json` because `yarn extract` will override the change since we can not use `\u2013` in `pages/servers.tsx`. 

Will think about another solution.

**Comment by roydigerhund** [comment]
Both of those solutions would work, on `yarn extract` they will create the same code with the decoded `–` in `en.json`.

```ts
defaultMessage="… provider – we call …"
```

```ts
defaultMessage={`… provider \u2013 we call …`}
```

**Comment by roydigerhund** [comment]
@Gargron is there a way to batch update the translation? Changing the wrong dashes in every language manually takes a while.

**Comment by renchap** [comment]
Looks like there is a way to import files in batch: https://support.crowdin.com/uploading-translations/#mass-translations-upload

**Comment by roydigerhund** [comment]
@renchap I don't have the upload button in crowdin, this feature is maybe limited to certain account types.

**Pull request closed without merging**
